name: Tag branch
on:
  push:
    branches:
      - feature
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout git repo
      uses: actions/checkout@master
    
    - name: Bump version and push tag
      uses: Rajanandhini97/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

